name: CI

on: [push]

jobs:
  sast_scan:
    #bandit - sast tool for python
    name: Run Bandit Scan
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.1

    - name: Setup Python
      uses: actions/setup-python@v5.0.0
      with: 
        python-version: 3.8

    - name: Install Bandit
      run: pip install bandit

    - name: Run Bandit Scan
      run: bandit -ll -ii  -r . -f json -o bandit-report.json
      # note: report is for machine consumption for use in vuln management tools like DefectDojo

    - name: Upload Artifact
      uses: actions/upload-artifact@v4.0.0
      if: always()
      with:
        name: bandkt-findings
        path: bandit-report.json
      
      
      

    
      
      
        
